### PR TITLE
Implement restore_state for color_temp & only turn on lights that were previously on

### PR DESCRIPTION
**Pull request by Breina**

### CODE REVIEW

**Comment by Breina** [comment]
Also added an implementation for fixed.
Might have misinterpreted its purpose, is it meant to just ignore state updates?
My current implementation is for lights than can go on or off, but can't be dimmed. Should that have been a different type instead?

**Comment by mvandenabeele** [comment]
Somehow, I missed your PR. Thanks for that. I'll merge it in my repository, but that is not the main repository advertised in the Home Assistant community forum.

**Review by mvandenabeele — COMMENTED** [review]
Great fixes

**Comment by Breina** [comment]
Thanks for merging! I don't care which one is advertised on the forums, yours is ahead so I use yours. :)

**Pull request merged**
